/**
 * lib/agent-task-win32.mjs: the per-agent logon Scheduled Task that is the
 * product supervisor on Windows (design 4, Windows bullet; G7). The spec builder
 * is pure and pinned here as EXACT text, because the two generated files are the
 * whole contract with Task Scheduler and wscript and nothing else checks them:
 *
 *   run-agent.vbs           a minimized console running
 *                           node <plugin root>\bin\hoai-core.mjs --keep-alive in the
 *                           agent folder, waiting on it and handing back its exit code
 *   install-agent-task.ps1  Register-ScheduledTask for the CURRENT user, unelevated
 *                           (the watcher's own pattern, lib/watcher-service.mjs):
 *                           AtLogOn, RestartCount 999, RestartInterval 1 minute,
 *                           ExecutionTimeLimit 0, MultipleInstances IgnoreNew,
 *                           action wscript.exe //B <statedir>\run-agent.vbs
 *   supervisor-generation   2 (design 4 generation stamp)
 *
 * The runners go through an injected exec + fs; nothing here runs schtasks or
 * PowerShell for real.
 *
 * Run: npx tsx --test test/agent-task-win32.test.ts
 */

import { test } from 'node:test'
import assert from 'node:assert/strict'

import {
  AGENT_TASK_SCRIPT_FILE_NAME,
  agentTaskSpec,
  installAgentTask,
  runAgentTask,
  uninstallAgentTask,
} from '../lib/agent-task-win32.mjs'
import { AGENT_TASK_LAUNCHER_FILE_NAME, agentTaskName, resolveAgentSupervisor } from '../lib/agent-inventory.mjs'
import { memoryFs } from './helpers/memory-fs.ts'

const HOME = 'C:\\Users\\kc'
const NODE = 'C:\\Program Files\\nodejs\\node.exe'
const ROOT = 'C:\\Users\\kc\\.claude\\plugins\\cache\\hoai\\hoai\\0.62.0'
const CWD = 'C:\\Users\\kc\\hoai-agents\\ava'
const STATE = 'C:\\Users\\kc\\.bgos-agent\\912'

function spec() {
  return agentTaskSpec({ assistantId: '912', home: HOME, nodePath: NODE, pluginRoot: ROOT, cwd: CWD })
}

function recordingExec(codes: Record<string, number> = {}) {
  const calls: Array<{ file: string; args: string[] }> = []
  const exec = async (file: string, args: readonly string[]) => {
    calls.push({ file, args: [...args] })
    const key = Object.keys(codes).find((k) => `${file} ${args.join(' ')}`.includes(k))
    const code = key ? codes[key]! : 0
    return { code, stdout: code === 0 ? 'ok' : '', stderr: code === 0 ? '' : 'Access is denied.', error: null, timedOut: false }
  }
  return { calls, exec }
}

test('agentTaskSpec: names and paths (task "HOAI Agent <id>", files in the agent state dir)', () => {
  const s = spec()
  assert.equal(s.taskName, 'HOAI Agent 912')
  assert.equal(s.taskName, agentTaskName('912'))
  assert.equal(s.stateDir, STATE)
  assert.equal(s.launcherPath, `${STATE}\\${AGENT_TASK_LAUNCHER_FILE_NAME}`)
  assert.equal(s.scriptPath, `${STATE}\\${AGENT_TASK_SCRIPT_FILE_NAME}`)
  assert.deepEqual(s.files.map((f: any) => f.path), [s.launcherPath, s.scriptPath, `${STATE}\\supervisor-generation`])
  assert.equal(s.files[2].content, '2\n')
})

test('run-agent.vbs: exact text, a minimized console (7) running hoai-core --keep-alive in the agent folder, waiting, exit code handed back', () => {
  const vbs = spec().files[0].content
  assert.equal(
    vbs,
    [
      "' HOAI Agent 912: run this agent's hoai launcher (--keep-alive) in a minimized console.",
      "' Generated by lib/agent-task-win32.mjs; the Scheduled Task 'HOAI Agent 912' runs this at logon.",
      'Set shell = CreateObject("WScript.Shell")',
      'shell.CurrentDirectory = "C:\\Users\\kc\\hoai-agents\\ava"',
      'WScript.Quit shell.Run("""C:\\Program Files\\nodejs\\node.exe"" ""C:\\Users\\kc\\.claude\\plugins\\cache\\hoai\\hoai\\0.62.0\\bin\\hoai-core.mjs"" --keep-alive", 7, True)',
      '',
    ].join('\r\n'),
  )
})

test('install-agent-task.ps1: exact text, unelevated Register-ScheduledTask with the design 4 settings', () => {
  const ps1 = spec().files[1].content
  assert.equal(
    ps1,
    [
      '# HOAI Agent 912: logon task that keeps this agent running (generated by lib/agent-task-win32.mjs).',
      'param([Parameter(Mandatory = $true)][ValidateSet("install", "run", "uninstall", "status")][string]$Action)',
      "$name = 'HOAI Agent 912'",
      "$vbs = 'C:\\Users\\kc\\.bgos-agent\\912\\run-agent.vbs'",
      'function Register-Task {',
      '  $action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "//B `"$vbs`""',
      '  $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME',
      '  $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -MultipleInstances IgnoreNew',
      '  $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited',
      '  Register-ScheduledTask -TaskName $name -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force -ErrorAction Stop | Out-Null',
      '}',
      'switch ($Action) {',
      '  "install" {',
      '    try { Register-Task; Write-Output "task registered"; exit 0 }',
      '    catch { Write-Output ("task registration refused: " + $_.Exception.Message); exit 1 }',
      '  }',
      '  "run" {',
      '    try { Start-ScheduledTask -TaskName $name -ErrorAction Stop; Write-Output "task started"; exit 0 }',
      '    catch { Write-Output ("task start refused: " + $_.Exception.Message); exit 1 }',
      '  }',
      '  "uninstall" {',
      '    try { Unregister-ScheduledTask -TaskName $name -Confirm:$false -ErrorAction Stop } catch {}',
      '    Write-Output "unregistered"; exit 0',
      '  }',
      '  "status" {',
      '    $task = Get-ScheduledTask -TaskName $name -ErrorAction SilentlyContinue',
      '    if ($task) { Write-Output ("task " + $task.State); exit 0 }',
      '    Write-Output "not registered"; exit 1',
      '  }',
      '}',
      '',
    ].join('\r\n'),
  )
})

test('agentTaskSpec: commands (PowerShell -File for install/uninstall/status, schtasks /Run /TN for a start)', () => {
  const s = spec()
  const ps = (action: string) => ({ file: 'powershell.exe', args: ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', s.scriptPath, '-Action', action] })
  assert.deepEqual(s.installCommands, [ps('install')])
  assert.deepEqual(s.uninstallCommands, [ps('uninstall')])
  assert.deepEqual(s.statusCommands, [ps('status')])
  assert.deepEqual(s.runCommands, [{ file: 'schtasks.exe', args: ['/Run', '/TN', 'HOAI Agent 912'] }])
})

test('agentTaskSpec: a quote in any embedded path, a junk id or a missing path throws before anything is written', () => {
  const ok = { assistantId: '912', home: HOME, nodePath: NODE, pluginRoot: ROOT, cwd: CWD }
  for (const [name, patch] of [
    ['quote in cwd', { cwd: 'C:\\Users\\kc\\o"brien' }],
    ['apostrophe in home', { home: "C:\\Users\\o'brien" }],
    ['quote in node', { nodePath: 'C:\\x"\\node.exe' }],
    ['quote in plugin root', { pluginRoot: "C:\\it's" }],
    ['junk id', { assistantId: '9 12' }],
    ['no cwd', { cwd: '' }],
    ['no plugin root', { pluginRoot: '' }],
    ['no node', { nodePath: '' }],
  ] as const) {
    assert.throws(() => agentTaskSpec({ ...ok, ...(patch as any) }), /agentTaskSpec/, name)
  }
})

test('installAgentTask: writes the three files, registers, then starts only when asked; the inventory then sees a canonical service', async () => {
  const fs = memoryFs()
  const rec = recordingExec()
  const s = spec()
  const res = await installAgentTask(s, { exec: rec.exec, fs, start: true })
  assert.equal(res.ok, true)
  assert.deepEqual(rec.calls.map((c) => c.file), ['powershell.exe', 'schtasks.exe'])
  assert.deepEqual(rec.calls[0]!.args.slice(-2), ['-Action', 'install'])
  for (const f of s.files) assert.equal(fs.files.get(f.path), f.content)
  const resolved = resolveAgentSupervisor({ platform: 'win32', home: HOME, assistantId: '912', exists: fs.exists, readFile: fs.readFile, pidAlive: () => false })
  assert.equal(resolved.service?.kind, 'schtasks')
  // Not started when the agent may be running by hand: never a second session.
  const quiet = recordingExec()
  await installAgentTask(s, { exec: quiet.exec, fs: memoryFs(), start: false })
  assert.deepEqual(quiet.calls.map((c) => c.file), ['powershell.exe'])
})

test('installAgentTask: a refused registration is a named failure and starts nothing', async () => {
  const rec = recordingExec({ '-Action install': 1 })
  const res = await installAgentTask(spec(), { exec: rec.exec, fs: memoryFs(), start: true })
  assert.equal(res.ok, false)
  assert.match(res.message, /install-agent-task\.ps1 -Action install failed \(rc 1\): Access is denied\./)
  assert.equal(rec.calls.length, 1)
})

test('runAgentTask: schtasks /Run /TN "HOAI Agent <id>", a non-zero rc is a named failure', async () => {
  const rec = recordingExec()
  assert.deepEqual(await runAgentTask(spec(), { exec: rec.exec }), { ok: true, message: 'schtasks.exe /Run /TN HOAI Agent 912 ok' })
  const bad = recordingExec({ '/Run': 1 })
  const res = await runAgentTask(spec(), { exec: bad.exec })
  assert.equal(res.ok, false)
  assert.match(res.message, /rc 1/)
})

test('uninstallAgentTask: unregisters and removes only its own files (the session pin stays)', async () => {
  const s = spec()
  const fs = memoryFs({ [`${STATE}\\session-id`]: 'pin' })
  await installAgentTask(s, { exec: recordingExec().exec, fs, start: false })
  const rec = recordingExec()
  const res = await uninstallAgentTask(s, { exec: rec.exec, fs })
  assert.equal(res.ok, true)
  assert.deepEqual(rec.calls[0]!.args.slice(-2), ['-Action', 'uninstall'])
  for (const f of s.files) assert.equal(fs.files.has(f.path), false)
  assert.equal(fs.files.get(`${STATE}\\session-id`), 'pin')
})
