/**
 * The Sessions library, Claude Code side (P6 stage 3, C-32, spec 5.7): the
 * sessions in this agent's own folder, listed for the app's Sessions sheet.
 *
 * What the owner reads in that sheet came from THEIR computer, and some of it
 * was typed in a terminal and never passed through HOAI, so these tests pin
 * three things before anything else:
 *
 * 1. The title is the right one: the owner's own name for the session
 *    (custom-title), else Claude Code's (ai-title), else the first thing the
 *    owner said, with the HOAI channel envelope taken off and never a tool
 *    result, a harness line, a peer or a system message.
 * 2. A title or preview that holds a secret is withheld WHOLE, never masked
 *    and never searched (D24).
 * 3. The read is bounded: the 200 newest top level transcripts at most, the
 *    first and last 64 KB of each, and an unchanged file is not read again.
 *
 * Fixture lines mirror the real entry shapes of a Claude Code 2.1.x
 * transcript on this machine (read by entry type and key names only).
 */

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, writeFileSync, utimesSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  AgentSessionLibrary,
  listAgentSessions,
  SESSION_READ_BYTES,
  SESSION_SCAN_MAX,
  type SessionLibraryFs,
} from '../lib/session-library.ts'
import { scanText } from '../lib/secret-scan.ts'
import {
  SESSION_BRANCH_MAX,
  SESSION_PREVIEW_MAX,
  SESSION_TITLE_MAX,
  SESSIONS_LIST_MAX,
} from '../lib/session-controls-contract.ts'

// ── Fixtures ────────────────────────────────────────────────────────────────

const DIR = '/home/owner/.claude/projects/-home-owner-agents-atlas'

/** A session id the way Claude Code mints them (a UUID). */
function sid(n: number): string {
  const s = String(n)
  return `${s.padStart(8, '0')}-1111-4222-8333-${s.padStart(12, '0')}`
}
const file = (n: number): string => `${sid(n)}.jsonl`

const line = (o: unknown): string => JSON.stringify(o)
const transcript = (...lines: string[]): string => `${lines.join('\n')}\n`

const customTitle = (t: string): string =>
  line({ type: 'custom-title', customTitle: t, sessionId: 's' })
const aiTitle = (t: string): string => line({ type: 'ai-title', aiTitle: t, sessionId: 's' })
const lastPrompt = (t: string): string =>
  line({ type: 'last-prompt', lastPrompt: t, leafUuid: 'l', sessionId: 's' })
/** The CLI also writes last-prompt entries with no lastPrompt at all. */
const lastPromptBare = (): string => line({ type: 'last-prompt', leafUuid: 'l', sessionId: 's' })

/** Typed in the terminal by the owner. */
const typed = (text: string, extra: Record<string, unknown> = {}): string =>
  line({
    type: 'user',
    isSidechain: false,
    promptId: 'p',
    origin: { kind: 'human' },
    message: { role: 'user', content: text },
    ...extra,
  })

/** A HOAI channel message, as the CLI records it (isMeta, origin channel). */
function channel(body: string, attrs: Record<string, string> = {}): string {
  const extra = Object.entries(attrs)
    .map(([k, v]) => ` ${k}="${v}"`)
    .join('')
  return line({
    type: 'user',
    isMeta: true,
    isSidechain: false,
    promptId: 'p',
    origin: { kind: 'channel', server: 'plugin:hoai:bgos' },
    message: {
      role: 'user',
      content:
        `<channel source="plugin:hoai:bgos" chat_id="12" message_id="7" user="Kc" ` +
        `user_id="3" assistant_id="901" ts="2026-09-25T08:00:00.000Z" transport="ws" ` +
        `is_shared_recipient="false"${extra}>\n${body}\n</channel>`,
    },
  })
}

const toolResult = (text: string): string =>
  line({
    type: 'user',
    isSidechain: false,
    message: {
      role: 'user',
      content: [{ type: 'tool_result', tool_use_id: 't', content: [{ type: 'text', text }] }],
    },
  })

const assistant = (text: string, extra: Record<string, unknown> = {}): string =>
  line({
    type: 'assistant',
    isSidechain: false,
    requestId: 'r',
    message: { role: 'assistant', content: [{ type: 'text', text }] },
    ...extra,
  })

const caveat = (): string =>
  line({
    type: 'user',
    isMeta: true,
    isSidechain: false,
    message: {
      role: 'user',
      content: '<local-command-caveat>Caveat: the messages below were generated by the user</local-command-caveat>',
    },
  })

const slashCommand = (): string =>
  line({
    type: 'user',
    isSidechain: false,
    message: {
      role: 'user',
      content: '<command-name>/goal</command-name>\n<command-message>goal</command-message>',
    },
  })

const taskNotification = (): string =>
  line({
    type: 'user',
    isSidechain: false,
    origin: { kind: 'task-notification' },
    message: { role: 'user', content: '<task-notification>worker finished</task-notification>' },
  })

/**
 * A fake GitHub token, assembled at run time so this source file never holds
 * a literal a repository scanner would flag. lib/secret-scan.ts's
 * github_token rule matches it (asserted before it is used).
 */
const FAKE_TOKEN = ['ghp', '_', 'A1b2C3d4E5f6G7h8I9j0K1l2'].join('')

interface FakeFile {
  text: string
  mtimeMs: number
  unreadable?: boolean
  statFails?: boolean
  folder?: boolean
}

interface Reads {
  head: Array<{ name: string; bytes: number }>
  tail: Array<{ name: string; bytes: number }>
}

/** An in memory agent folder. Paths are matched by their last segment, so
 *  the library's own join() on Windows or POSIX reaches the same file. */
function fakeFs(files: Record<string, FakeFile>): SessionLibraryFs & { reads: Reads } {
  const reads: Reads = { head: [], tail: [] }
  const name = (p: string): string => p.split(/[\\/]/).pop() ?? ''
  const get = (p: string): FakeFile => {
    const f = files[name(p)]
    if (!f) throw new Error(`ENOENT: ${p}`)
    return f
  }
  return {
    reads,
    list: (dir: string) => {
      assert.equal(dir, DIR, 'the library lists the folder it was given')
      return Object.keys(files)
    },
    stat: (p: string) => {
      const f = get(p)
      if (f.statFails) throw new Error(`EPERM: ${p}`)
      return { mtimeMs: f.mtimeMs, size: Buffer.byteLength(f.text), isFile: f.folder !== true }
    },
    readHead: (p: string, bytes: number) => {
      const f = get(p)
      reads.head.push({ name: name(p), bytes })
      if (f.unreadable) throw new Error(`EACCES: ${p}`)
      return Buffer.from(f.text).subarray(0, bytes).toString('utf8')
    },
    readTail: (p: string, bytes: number) => {
      const f = get(p)
      reads.tail.push({ name: name(p), bytes })
      if (f.unreadable) throw new Error(`EACCES: ${p}`)
      const b = Buffer.from(f.text)
      return b.subarray(Math.max(0, b.length - bytes)).toString('utf8')
    },
  }
}

function list(
  files: Record<string, FakeFile>,
  over: { currentName?: string | null; query?: string; limit?: number } = {},
) {
  const fs = fakeFs(files)
  const answer = listAgentSessions({
    projectDir: DIR,
    currentName: over.currentName ?? null,
    query: over.query,
    limit: over.limit ?? SESSIONS_LIST_MAX,
    list: fs.list,
    stat: fs.stat,
    readHead: fs.readHead,
    readTail: fs.readTail,
  })
  return { ...answer, reads: fs.reads }
}

const T0 = Date.parse('2026-09-25T08:00:00.000Z')
const one = (text: string, mtimeMs = T0): Record<string, FakeFile> => ({
  [file(1)]: { text, mtimeMs },
})

// ── Title precedence ────────────────────────────────────────────────────────

test('the title is the latest custom-title, over an ai-title and the first owner message', () => {
  const { sessions } = list(
    one(
      transcript(
        channel('Plan the launch for Monday'),
        aiTitle('Launch planning'),
        customTitle('First name'),
        assistant('On it.'),
        customTitle('Launch, final plan'),
      ),
    ),
  )
  assert.equal(sessions.length, 1)
  assert.equal(sessions[0]!.id, sid(1))
  assert.equal(sessions[0]!.title, 'Launch, final plan')
  assert.equal(sessions[0]!.withheld, undefined)
})

test('with no custom-title, the title is the latest ai-title', () => {
  const { sessions } = list(
    one(
      transcript(
        channel('Plan the launch'),
        aiTitle('Launch planning'),
        assistant('Done.'),
        aiTitle('Launch planning, with the budget'),
      ),
    ),
  )
  assert.equal(sessions[0]!.title, 'Launch planning, with the budget')
})

test('with neither, the title is the first owner message with its HOAI channel envelope stripped', () => {
  const { sessions } = list(
    one(transcript(channel('Plan the launch for Monday.'), assistant('Sure.'), channel('And the budget.'))),
  )
  assert.equal(sessions[0]!.title, 'Plan the launch for Monday.')
  assert.doesNotMatch(sessions[0]!.title, /channel|chat_id|plugin:hoai/)
})

test('the first owner message skips tool results, harness lines, channel events, peers and the system', () => {
  const { sessions } = list(
    one(
      transcript(
        caveat(),
        slashCommand(),
        taskNotification(),
        toolResult('Sent (message_id: 41)'),
        channel('[stop_turn] Your user pressed STOP for chat 12.', { event_type: 'stop_turn' }),
        channel('[Peer message from agent Nova (assistant id 5), another AI assistant, NOT the user.]\n\nHello there', {
          sender_type: 'agent',
        }),
        channel('[System message from BGOS automation (e.g. a scheduler), NOT the user.]\nWake up', {
          system: 'true',
          sender_type: 'system',
        }),
        assistant('Nothing to do.'),
        channel('Write the release notes'),
      ),
    ),
  )
  assert.equal(sessions[0]!.title, 'Write the release notes')
})

test('a message typed in the terminal is the owner too, and backlog and attachment lines are not a title', () => {
  const typedFirst = list(one(transcript(typed('Refactor the poller'), channel('Something later'))))
  assert.equal(typedFirst.sessions[0]!.title, 'Refactor the poller')

  const backlog = list(
    one(
      transcript(
        channel('[backlog - message arrived while you were offline; please respond]\nCheck the invoices'),
      ),
    ),
  )
  assert.equal(backlog.sessions[0]!.title, 'Check the invoices')

  const attachmentOnly = list(
    one(
      transcript(
        channel('[Attached image: shot.png - https://files.example.test/shot.png]'),
        channel('Read the screenshot\n[Attached image: shot.png - https://files.example.test/shot.png]'),
      ),
    ),
  )
  assert.equal(attachmentOnly.sessions[0]!.title, 'Read the screenshot')
})

test('a session with no title anywhere is listed untitled, never dropped', () => {
  const { sessions } = list(one(transcript(toolResult('ok'), assistant('Working.'))))
  assert.equal(sessions.length, 1)
  assert.equal(sessions[0]!.title, '')
  assert.equal(sessions[0]!.withheld, undefined)
})

// ── Preview, branch, last activity ──────────────────────────────────────────

test('the preview is the latest last-prompt, else the last assistant text', () => {
  const withPrompt = list(
    one(
      transcript(
        channel('Plan the launch'),
        lastPrompt('Plan the launch'),
        assistant('Planned.'),
        lastPrompt('Now the budget'),
        lastPromptBare(),
        assistant('Budget done.'),
      ),
    ),
  )
  assert.equal(withPrompt.sessions[0]!.preview, 'Now the budget')

  const withoutPrompt = list(
    one(
      transcript(
        channel('Plan the launch'),
        assistant('First answer.'),
        assistant('The plan is ready.'),
        assistant('API Error: overloaded', { isApiErrorMessage: true }),
      ),
    ),
  )
  assert.equal(withoutPrompt.sessions[0]!.preview, 'The plan is ready.')

  const nothing = list(one(transcript(customTitle('Named'))))
  assert.equal(nothing.sessions[0]!.preview, null)
})

test('the branch is the latest gitBranch, and the last activity is the file mtime', () => {
  const mtime = Date.parse('2026-09-24T17:30:00.000Z')
  const { sessions } = list(
    one(
      transcript(
        typed('Start', { gitBranch: 'main' }),
        assistant('ok', { gitBranch: 'feat/p6-stop-resume' }),
      ),
      mtime,
    ),
  )
  assert.equal(sessions[0]!.branch, 'feat/p6-stop-resume')
  assert.equal(sessions[0]!.lastActivityAt, '2026-09-24T17:30:00.000Z')

  const noBranch = list(one(transcript(customTitle('Named'))))
  assert.equal(noBranch.sessions[0]!.branch, null)
})

// ── Secrets (D24) ───────────────────────────────────────────────────────────

test('the fake token really is a secret to lib/secret-scan.ts, so the cases below mean something', () => {
  assert.ok(scanText('fixture', FAKE_TOKEN).length > 0)
})

test('a title that holds a secret is withheld whole, never masked', () => {
  const custom = list(one(transcript(customTitle(`Rotate ${FAKE_TOKEN} today`), aiTitle('Key rotation'))))
  assert.equal(custom.sessions[0]!.title, '')
  assert.equal(custom.sessions[0]!.withheld, 'secret')
  assert.ok(!JSON.stringify(custom.sessions).includes(FAKE_TOKEN.slice(0, 8)))

  // The first owner message: the secret sits on a later line, past what a
  // one line title would show. The whole field is still withheld.
  const firstMessage = list(
    one(transcript(channel(`Set up the deploy\nuse this key:\ntoken = ${FAKE_TOKEN}`))),
  )
  assert.equal(firstMessage.sessions[0]!.title, '')
  assert.equal(firstMessage.sessions[0]!.withheld, 'secret')
})

test('a preview that holds a secret is left out, and a clean title stays', () => {
  const { sessions } = list(
    one(transcript(customTitle('Deploy'), lastPrompt(`push with ${FAKE_TOKEN}`))),
  )
  assert.equal(sessions[0]!.title, 'Deploy')
  assert.equal(sessions[0]!.withheld, undefined)
  assert.equal(sessions[0]!.preview, null)
  assert.ok(!JSON.stringify(sessions).includes(FAKE_TOKEN.slice(0, 8)))
})

test('a withheld title or preview is never searched', () => {
  const files = {
    [file(1)]: { text: transcript(customTitle(`secret ${FAKE_TOKEN}`)), mtimeMs: T0 },
    [file(2)]: { text: transcript(customTitle('Plain'), lastPrompt(`secret ${FAKE_TOKEN}`)), mtimeMs: T0 - 1 },
  }
  assert.equal(list(files, { query: 'secret' }).sessions.length, 0)
  assert.equal(list(files, { query: 'ghp' }).sessions.length, 0)
})

// ── Caps and cleaning ───────────────────────────────────────────────────────

test('title, preview and branch are one clean line, capped at the contract limits', () => {
  const long = 'word '.repeat(100)
  const { sessions } = list(
    one(
      transcript(
        customTitle(`  Two\nlines\u0007 and\ta \u202etab   ${long}`),
        lastPrompt(`${'p'.repeat(SESSION_PREVIEW_MAX - 1)}\u{1F600}tail`),
        assistant('x', { gitBranch: `feat/${'b'.repeat(100)}` }),
      ),
    ),
  )
  const row = sessions[0]!
  assert.ok(row.title.startsWith('Two lines and a tab word word'), row.title)
  assert.ok(Array.from(row.title).length <= SESSION_TITLE_MAX)
  assert.doesNotMatch(row.title, /[\u0000-\u001f\u007f\u202e]/)
  assert.equal(row.title, row.title.trim())
  // Capped in characters, and an emoji at the edge is never cut in half.
  assert.equal(Array.from(row.preview!).length, SESSION_PREVIEW_MAX)
  assert.ok(row.preview!.endsWith('\u{1F600}'))
  assert.equal(Array.from(row.branch!).length, SESSION_BRANCH_MAX)
})

// ── Order, Current, query, the cap ──────────────────────────────────────────

test('rows are newest first, and only the bound session is Current', () => {
  const files = {
    [file(1)]: { text: transcript(customTitle('Oldest')), mtimeMs: T0 - 2_000 },
    [file(2)]: { text: transcript(customTitle('Middle')), mtimeMs: T0 - 1_000 },
    [file(3)]: { text: transcript(customTitle('Newest')), mtimeMs: T0 },
  }
  const { sessions, truncated } = list(files, { currentName: file(2) })
  assert.deepEqual(
    sessions.map((r) => [r.title, r.current]),
    [
      ['Newest', false],
      ['Middle', true],
      ['Oldest', false],
    ],
  )
  assert.equal(truncated, false)
  assert.equal(list(files).sessions.filter((r) => r.current).length, 0)
})

test('the query filters title and preview, folding case and accents, before the cap', () => {
  const files: Record<string, FakeFile> = {}
  for (let i = 1; i <= 8; i++) {
    files[file(i)] = { text: transcript(customTitle(`Other ${i}`)), mtimeMs: T0 - i }
  }
  files[file(20)] = { text: transcript(customTitle('Résumé draft')), mtimeMs: T0 - 100 }
  files[file(21)] = { text: transcript(customTitle('Notes'), lastPrompt('the RESUME budget')), mtimeMs: T0 - 101 }
  const { sessions } = list(files, { query: '  resume ', limit: 5 })
  assert.deepEqual(
    sessions.map((r) => r.id),
    [sid(20), sid(21)],
  )
  assert.equal(list(files, { query: 'nothing like this' }).sessions.length, 0)
})

test('at most limit rows, and one match past the cap says truncated', () => {
  const files: Record<string, FakeFile> = {}
  for (let i = 1; i <= 6; i++) files[file(i)] = { text: transcript(customTitle(`S${i}`)), mtimeMs: T0 - i }
  const cut = list(files, { limit: 5 })
  assert.equal(cut.sessions.length, 5)
  assert.equal(cut.truncated, true)
  const exact = list(files, { limit: 6 })
  assert.equal(exact.sessions.length, 6)
  assert.equal(exact.truncated, false)
})

test('the limit is never above the contract maximum of 50', () => {
  const files: Record<string, FakeFile> = {}
  for (let i = 1; i <= 60; i++) files[file(i)] = { text: transcript(customTitle(`S${i}`)), mtimeMs: T0 - i }
  const { sessions, truncated } = list(files, { limit: 500 })
  assert.equal(sessions.length, SESSIONS_LIST_MAX)
  assert.equal(truncated, true)
})

test('the Current row is kept when the cap cuts it', () => {
  const files: Record<string, FakeFile> = {}
  for (let i = 1; i <= 8; i++) files[file(i)] = { text: transcript(customTitle(`S${i}`)), mtimeMs: T0 - i }
  const { sessions, truncated } = list(files, { limit: 3, currentName: file(8) })
  assert.deepEqual(
    sessions.map((r) => r.id),
    [sid(1), sid(2), sid(8)],
  )
  assert.equal(sessions[2]!.current, true)
  assert.equal(truncated, true)
})

// ── The read bound ──────────────────────────────────────────────────────────

test(`only the ${SESSION_SCAN_MAX} newest transcripts are ever read, and past them the answer says truncated`, () => {
  assert.equal(SESSION_SCAN_MAX, 200)
  const files: Record<string, FakeFile> = {}
  for (let i = 1; i <= 205; i++) files[file(i)] = { text: transcript(customTitle(`S${i}`)), mtimeMs: T0 - i }
  const searched = list(files, { query: 'no session has this title' })
  assert.equal(searched.sessions.length, 0)
  assert.equal(searched.truncated, true)
  const read = new Set(searched.reads.head.map((r) => r.name))
  assert.equal(read.size, 200)
  for (let i = 201; i <= 205; i++) assert.ok(!read.has(file(i)), `${file(i)} is past the bound`)
})

test('without a query the scan stops one row past the cap', () => {
  const files: Record<string, FakeFile> = {}
  for (let i = 1; i <= 60; i++) files[file(i)] = { text: transcript(customTitle(`S${i}`)), mtimeMs: T0 - i }
  const { reads } = list(files, { limit: 10 })
  assert.equal(reads.head.length, 11)
})

test('each large transcript is read as its first and last 64 KB, never whole', () => {
  assert.equal(SESSION_READ_BYTES, 64 * 1024)
  const filler = (n: number): string[] =>
    Array.from({ length: n }, (_, i) => assistant(`filler ${i} ${'z'.repeat(10_000)}`))
  const text = transcript(
    aiTitle('From the head'),
    ...filler(8),
    customTitle('From the middle, never read'),
    ...filler(8),
    lastPrompt('From the tail'),
  )
  assert.ok(Buffer.byteLength(text) > 2 * SESSION_READ_BYTES + 20_000)
  const { sessions, reads } = list(one(text))
  assert.equal(sessions[0]!.title, 'From the head')
  assert.equal(sessions[0]!.preview, 'From the tail')
  assert.deepEqual(reads.head, [{ name: file(1), bytes: SESSION_READ_BYTES }])
  assert.deepEqual(reads.tail, [{ name: file(1), bytes: SESSION_READ_BYTES }])
})

test('a small transcript is read once, whole', () => {
  const text = transcript(channel('Hello'), customTitle('Small'))
  const { sessions, reads } = list(one(text))
  assert.equal(sessions[0]!.title, 'Small')
  assert.deepEqual(reads.head, [{ name: file(1), bytes: Buffer.byteLength(text) }])
  assert.deepEqual(reads.tail, [])
})

// ── What is listed at all ───────────────────────────────────────────────────

test('only top level session transcripts are listed', () => {
  const files: Record<string, FakeFile> = {
    [file(1)]: { text: transcript(customTitle('Real')), mtimeMs: T0 },
    'notes.txt': { text: 'x', mtimeMs: T0 + 5 },
    'agent-1a2b3c4d.jsonl': { text: transcript(customTitle('A subagent')), mtimeMs: T0 + 4 },
    'bad name.jsonl': { text: transcript(customTitle('Odd')), mtimeMs: T0 + 3 },
    [sid(7)]: { text: 'a folder', mtimeMs: T0 + 2, folder: true },
    [`${sid(8)}.jsonl`]: { text: 'a folder', mtimeMs: T0 + 1, folder: true },
  }
  const { sessions } = list(files)
  assert.deepEqual(
    sessions.map((r) => r.title),
    ['Real'],
  )
})

test('an empty or unreadable transcript is skipped, and the rest are listed', () => {
  const files: Record<string, FakeFile> = {
    [file(1)]: { text: '', mtimeMs: T0 },
    [file(2)]: { text: transcript(customTitle('Locked')), mtimeMs: T0 - 1, unreadable: true },
    [file(3)]: { text: transcript(customTitle('No stat')), mtimeMs: T0 - 2, statFails: true },
    [file(4)]: { text: transcript(customTitle('Fine')), mtimeMs: T0 - 3 },
  }
  const { sessions } = list(files)
  assert.deepEqual(
    sessions.map((r) => r.id),
    [sid(4)],
  )
})

// ── The cache ───────────────────────────────────────────────────────────────

test('an unchanged transcript is not read again, and a changed mtime or size reads it again', () => {
  const files: Record<string, FakeFile> = {
    [file(1)]: { text: transcript(customTitle('One')), mtimeMs: T0 },
    [file(2)]: { text: transcript(customTitle('Two')), mtimeMs: T0 - 1 },
  }
  const fs = fakeFs(files)
  const library = new AgentSessionLibrary({ projectDir: DIR, currentName: () => null, fs })

  assert.deepEqual(
    library.list({ limit: 50 }).sessions.map((r) => r.title),
    ['One', 'Two'],
  )
  assert.equal(fs.reads.head.length, 2)

  library.list({ limit: 50 })
  library.list({ query: 'one', limit: 50 })
  assert.equal(fs.reads.head.length, 2, 'unchanged files are served from the cache')

  files[file(1)]!.mtimeMs = T0 + 10
  files[file(1)]!.text = transcript(customTitle('One, renamed'))
  assert.equal(library.list({ limit: 50 }).sessions[0]!.title, 'One, renamed')
  assert.deepEqual(
    fs.reads.head.slice(2).map((r) => r.name),
    [file(1)],
  )

  // Same mtime, different size: read again too.
  files[file(2)]!.text = transcript(customTitle('Two, longer now'))
  assert.equal(library.list({ limit: 50 }).sessions[1]!.title, 'Two, longer now')
  assert.deepEqual(
    fs.reads.head.slice(3).map((r) => r.name),
    [file(2)],
  )
})

test('the library asks for the bound session on every list', () => {
  const files: Record<string, FakeFile> = {
    [file(1)]: { text: transcript(customTitle('One')), mtimeMs: T0 },
    [file(2)]: { text: transcript(customTitle('Two')), mtimeMs: T0 - 1 },
  }
  let current: string | null = file(1)
  const library = new AgentSessionLibrary({
    projectDir: DIR,
    currentName: () => current,
    fs: fakeFs(files),
  })
  assert.deepEqual(
    library.list({ limit: 50 }).sessions.map((r) => r.current),
    [true, false],
  )
  current = file(2)
  assert.deepEqual(
    library.list({ limit: 50 }).sessions.map((r) => r.current),
    [false, true],
  )
  current = null
  assert.deepEqual(
    library.list({ limit: 50 }).sessions.map((r) => r.current),
    [false, false],
  )
})

// ── Real files ──────────────────────────────────────────────────────────────

test('on disk: newest first, a large file read at both ends, and a missing folder lists nothing', () => {
  const dir = mkdtempSync(join(tmpdir(), 'session-library-'))
  writeFileSync(join(dir, file(1)), transcript(channel('Older work')))
  const big = transcript(
    channel('Big session'),
    ...Array.from({ length: 16 }, (_, i) => assistant(`filler ${i} ${'z'.repeat(10_000)}`)),
    customTitle('Named at the end'),
  )
  writeFileSync(join(dir, file(2)), big)
  writeFileSync(join(dir, 'README.md'), 'not a session')
  utimesSync(join(dir, file(1)), new Date(T0 - 60_000), new Date(T0 - 60_000))
  utimesSync(join(dir, file(2)), new Date(T0), new Date(T0))

  const library = new AgentSessionLibrary({ projectDir: dir, currentName: () => file(2) })
  const { sessions, truncated } = library.list({ limit: 50 })
  assert.deepEqual(
    sessions.map((r) => [r.id, r.title, r.current]),
    [
      [sid(2), 'Named at the end', true],
      [sid(1), 'Older work', false],
    ],
  )
  assert.equal(sessions[0]!.lastActivityAt, new Date(T0).toISOString())
  assert.equal(truncated, false)

  const missing = new AgentSessionLibrary({ projectDir: join(dir, 'no-such-folder'), currentName: () => null })
  assert.deepEqual(missing.list({ limit: 50 }), { sessions: [], truncated: false })
})

// ── server.ts wiring (a source guard: server.ts cannot be imported) ─────────

test('server.ts lists the folder the context gauge reads, with its resolved binding as Current', () => {
  const server = readFileSync(new URL('../server.ts', import.meta.url), 'utf8').replace(/\r\n/g, '\n')
  const at = server.indexOf('const sessionLibrary = new AgentSessionLibrary({')
  assert.ok(at > 0, 'server.ts builds one AgentSessionLibrary')
  const block = server.slice(at, server.indexOf('\n})\n', at))
  assert.match(block, /projectDir: sessionBinder\.projectDirectory,/)
  assert.match(block, /currentName: \(\) => sessionBinder\.resolve\(\)\?\.binding\.name \?\? null,/)
  assert.ok(
    server.indexOf('const sessionBinder = new SessionTranscriptBinder(') < at,
    'the binder exists before the library that reads it',
  )

  const rpcAt = server.indexOf('const voiceRpc = new VoiceRpcHandler({')
  const deps = server.slice(rpcAt, server.indexOf('\n})\n', rpcAt))
  assert.match(deps, /listSessions: \(input\) => sessionLibrary\.list\(input\),/)
})
